interface Country {
  id: string;
  nameBn: string;
  nameEn: string;
  geoId: string;
  geoParentId: string;
}

export const countriesList: Country[] = [
  {
    id: "1",
    nameBn: "বাংলাদেশ",
    nameEn: "BANGLADESH",
    geoId: "0",
    geoParentId: "5556",
  },
  {
    id: "7032",
    nameBn: "আফগানিস্তান",
    nameEn: "AFGHANISTAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7033",
    nameBn: "আলবেনিয়া",
    nameEn: "ALBANIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7380",
    nameBn: "আলজেরিয়া",
    nameEn: "ALGERIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7035",
    nameBn: "আমেরিকান সামোয়া",
    nameEn: "AMERICAN SAMOA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8331",
    nameBn: "এন্ডোরা",
    nameEn: "ANDORRA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7430",
    nameBn: "এঙ্গোলা",
    nameEn: "ANGOLA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7036",
    nameBn: "আর্জেন্টিনা",
    nameEn: "ARGENTINA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7037",
    nameBn: "আর্মেনিয়া",
    nameEn: "ARMENIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5726",
    nameBn: "অস্ট্রেলিয়া",
    nameEn: "AUSTRALIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5928",
    nameBn: "অস্ট্রিয়া",
    nameEn: "AUSTRIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7038",
    nameBn: "আজারবাইজান",
    nameEn: "AZERBAIJAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7039",
    nameBn: "বাহামাস",
    nameEn: "BAHAMAS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5708",
    nameBn: "বাহরাইন",
    nameEn: "BAHRAIN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9880",
    nameBn: "বার্বাডোজ",
    nameEn: "BARBADOS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9182",
    nameBn: "বেলারুশ",
    nameEn: "BELARUS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5789",
    nameBn: "বেলজিয়াম",
    nameEn: "BELGIUM",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8985",
    nameBn: "বেলিজ",
    nameEn: "BELIZE",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9132",
    nameBn: "বেনিন",
    nameEn: "BENIN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "13779",
    nameBn: "বারমুডা",
    nameEn: "BERMUDA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7042",
    nameBn: "ভুটান",
    nameEn: "BHUTAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8933",
    nameBn: "বলিভিয়া",
    nameEn: "BOLIVIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8886",
    nameBn: "বসনিয়া ও হার্জেগোভিনা",
    nameEn: "BOSNIA AND HERZEGOVINA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7044",
    nameBn: "বতসোয়ানা",
    nameEn: "BOTSWANA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7045",
    nameBn: "ব্রাজিল",
    nameEn: "BRAZIL",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5784",
    nameBn: "ব্রুনাই",
    nameEn: "BRUNEI",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7046",
    nameBn: "বুলগেরিয়া",
    nameEn: "BULGARIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9081",
    nameBn: "বুর্কিনা ফাসো",
    nameEn: "BURKINA FASO",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8881",
    nameBn: "বুরুন্ডি",
    nameEn: "BURUNDI",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8835",
    nameBn: "কেপ ভার্দে",
    nameEn: "CABO VERDE",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7047",
    nameBn: "কম্বোডিয়া",
    nameEn: "CAMBODIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8480",
    nameBn: "ক্যামেরুন",
    nameEn: "CAMEROON",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5643",
    nameBn: "কানাডা",
    nameEn: "CANADA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8932",
    nameBn: "চিলি",
    nameEn: "CHILE",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5659",
    nameBn: "চীন",
    nameEn: "CHINA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7050",
    nameBn: "কলোম্বিয়া",
    nameEn: "COLOMBIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8882",
    nameBn: "কমোরস",
    nameEn: "COMOROS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9931",
    nameBn: "কঙ্গো",
    nameEn: "CONGO",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7052",
    nameBn: "কোস্টারিকা",
    nameEn: "COSTA RICA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7053",
    nameBn: "ক্রোয়েশিয়া",
    nameEn: "CROATIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8181",
    nameBn: "কিউবা",
    nameEn: "CUBA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7055",
    nameBn: "সাইপ্রাস",
    nameEn: "CYPRUS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8887",
    nameBn: "চেক প্রজাতন্ত্র",
    nameEn: "CZECHIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5936",
    nameBn: "ডেনমার্ক",
    nameEn: "DENMARK",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8883",
    nameBn: "জিবুতি",
    nameEn: "DJIBOUTI",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8934",
    nameBn: "ডোমিনিকান রিপাবলিক",
    nameEn: "DOMINICAN REPUBLIC",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8787",
    nameBn: "ইকুয়েডর",
    nameEn: "ECUADOR",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5787",
    nameBn: "মিশর",
    nameEn: "EGYPT",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9083",
    nameBn: "এল সালভাদর",
    nameEn: "EL SALVADOR",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8280",
    nameBn: "ইকুয়েটোরিয়াল গিনি",
    nameEn: "EQUATORIAL GUINEA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8830",
    nameBn: "ইরিত্রিয়া",
    nameEn: "ERITREA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7030",
    nameBn: "এস্তোনিয়া",
    nameEn: "ESTONIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7058",
    nameBn: "ইথিওপিয়া",
    nameEn: "ETHIOPIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7080",
    nameBn: "ফিজি",
    nameEn: "FIJI",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "6780",
    nameBn: "ফিনল্যান্ড",
    nameEn: "FINLAND",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5739",
    nameBn: "ফ্রান্স",
    nameEn: "FRANCE",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8530",
    nameBn: "গ্যাবন",
    nameEn: "GABON",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "13079",
    nameBn: "গাম্বিয়া",
    nameEn: "GAMBIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7081",
    nameBn: "জর্জিয়া",
    nameEn: "GEORGIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5916",
    nameBn: "জার্মানী",
    nameEn: "GERMANY",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7082",
    nameBn: "ঘানা",
    nameEn: "GHANA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5684",
    nameBn: "গ্রীস",
    nameEn: "GREECE",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8939",
    nameBn: "গুয়াতেমালা",
    nameEn: "GUATEMALA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8831",
    nameBn: "গিনি",
    nameEn: "GUINEA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9137",
    nameBn: "গিনি বিসাউ",
    nameEn: "GUINEA-BISSAU",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9082",
    nameBn: "গায়ানা",
    nameEn: "GUYANA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7131",
    nameBn: "হাইতি",
    nameEn: "HAITI",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8889",
    nameBn: "হন্ডুরাস",
    nameEn: "HONDURAS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "13629",
    nameBn: "হংকং",
    nameEn: "HONG KONG",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9136",
    nameBn: "হাঙ্গেরি",
    nameEn: "HUNGARY",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7031",
    nameBn: "আইসল্যান্ড",
    nameEn: "ICELAND",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5662",
    nameBn: "ভারত",
    nameEn: "INDIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5911",
    nameBn: "ইন্দোনেশিয়া",
    nameEn: "INDONESIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "6730",
    nameBn: "ইরান",
    nameEn: "IRAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "6782",
    nameBn: "ইরাক",
    nameEn: "IRAQ",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8680",
    nameBn: "আয়ারল্যান্ড",
    nameEn: "IRELAND",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5876",
    nameBn: "ইটালি",
    nameEn: "ITALY",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "12979",
    nameBn: "আইভরি কোস্ট",
    nameEn: "IVORY COAST",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8783",
    nameBn: "জামাইকা",
    nameEn: "JAMAICA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5881",
    nameBn: "জাপান",
    nameEn: "JAPAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5676",
    nameBn: "জর্ডান",
    nameEn: "JORDAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8080",
    nameBn: "কাজাখস্তান",
    nameEn: "KAZAKHSTAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5733",
    nameBn: "কেনিয়া",
    nameEn: "KENYA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8832",
    nameBn: "কিরিবাতি",
    nameEn: "KIRIBATI",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5634",
    nameBn: "কুয়েত",
    nameEn: "KUWAIT",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8931",
    nameBn: "কিরঘিজস্তান",
    nameEn: "KYRGYZSTAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9033",
    nameBn: "লাওস",
    nameEn: "LAOS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8988",
    nameBn: "লাটাভিয়া",
    nameEn: "LATVIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5906",
    nameBn: "লেবানন",
    nameEn: "LEBANON",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "6781",
    nameBn: "লাইবেরিয়া",
    nameEn: "LIBERIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5920",
    nameBn: "লিবিয়া",
    nameEn: "LIBIYA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8834",
    nameBn: "লিথুয়ানিয়া",
    nameEn: "LITHUANIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7137",
    nameBn: "লুক্সেমবার্গ",
    nameEn: "LUXEMBOURG",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "11330",
    nameBn: "ম্যাসেডোনিয়া",
    nameEn: "MACEDONIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "12879",
    nameBn: "মাদাগাস্কার",
    nameEn: "MADAGASCAR",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9130",
    nameBn: "মাদাগাস্কার",
    nameEn: "MADAGASCAR",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5632",
    nameBn: "মালয়েশিয়া",
    nameEn: "MALAYSIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7138",
    nameBn: "মালদ্বীপ",
    nameEn: "MALDIVES",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7431",
    nameBn: "মালি",
    nameEn: "MALI",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7381",
    nameBn: "মাল্টা",
    nameEn: "MALTA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8885",
    nameBn: "মার্শাল আইল্যান্ডস",
    nameEn: "MARSHALL ISLANDS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8780",
    nameBn: "মৌরিতানিয়া",
    nameEn: "MAURITANIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5890",
    nameBn: "মরিশাস",
    nameEn: "MAURITIUS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7180",
    nameBn: "মেক্সিকো",
    nameEn: "MEXICO",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8784",
    nameBn: "মাইক্রোনেশিয়া",
    nameEn: "MICRONESIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9135",
    nameBn: "মলদোভা",
    nameEn: "MOLDOVA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8888",
    nameBn: "মোনাকো",
    nameEn: "MONACO",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8987",
    nameBn: "মঙ্গোলিয়া",
    nameEn: "MONGOLIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9086",
    nameBn: "মন্টেনিগ্রো",
    nameEn: "MONTENEGRO",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5868",
    nameBn: "মরক্কো",
    nameEn: "MOROCCO",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8938",
    nameBn: "মোজাম্বিক",
    nameEn: "MOZAMBIQUE",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5730",
    nameBn: "মায়ানমার",
    nameEn: "MYANMAR",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7181",
    nameBn: "নামিবিয়া",
    nameEn: "NAMIBIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8833",
    nameBn: "নাউরু",
    nameEn: "NAURU",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7182",
    nameBn: "নেপাল",
    nameEn: "NEPAL",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5728",
    nameBn: "নেদারল্যান্ডস",
    nameEn: "NETHERLANDS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7280",
    nameBn: "নিউজিল্যান্ড",
    nameEn: "NEW ZEALAND",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8180",
    nameBn: "নিকারাগুয়া",
    nameEn: "NICARAGUA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9080",
    nameBn: "নাইজার",
    nameEn: "NIGER",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7184",
    nameBn: "নাইজেরিয়া",
    nameEn: "NIGERIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7432",
    nameBn: "নরওয়ে",
    nameEn: "NORWAY",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5636",
    nameBn: "ওমান",
    nameEn: "OMAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5923",
    nameBn: "পাকিস্তান",
    nameEn: "PAKISTAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8936",
    nameBn: "পালাউ",
    nameEn: "PALAU",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9031",
    nameBn: "প্যালেস্টাইন",
    nameEn: "PALESTINE STATE",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9133",
    nameBn: "পানামা",
    nameEn: "PANAMA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7980",
    nameBn: "পাপুয়া নিউগিনি",
    nameEn: "PAPUA NEW GUINEA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8481",
    nameBn: "প্যারাগুয়ে",
    nameEn: "PARAGUAY",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8935",
    nameBn: "পেরু",
    nameEn: "PERU",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5919",
    nameBn: "ফিলিপাইন",
    nameEn: "PHILIPPINES",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5737",
    nameBn: "পোল্যান্ড",
    nameEn: "POLAND",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5853",
    nameBn: "পর্তুগাল",
    nameEn: "PORTUGAL",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5686",
    nameBn: "কাতার",
    nameEn: "QATAR",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7830",
    nameBn: "রোমানিয়া",
    nameEn: "ROMANIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "6477",
    nameBn: "রাশিয়ান ফেডারেশন",
    nameEn: "RUSSIAN FEDERATION",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8982",
    nameBn: "রুয়াণ্ডা",
    nameEn: "RWANDA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5651",
    nameBn: "সৌদি আরব",
    nameEn: "SAUDI ARABIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8130",
    nameBn: "সেনেগাল",
    nameEn: "SENEGAL",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8786",
    nameBn: "সার্বিয়া",
    nameEn: "SERBIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8781",
    nameBn: "সিশেলস",
    nameEn: "SEYCHELLES",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5657",
    nameBn: "সিঙ্গাপুর",
    nameEn: "SINGAPORE",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8937",
    nameBn: "স্লোভাকিয়া",
    nameEn: "SLOVAKIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9087",
    nameBn: "স্লোভেনিয়া",
    nameEn: "SLOVENIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8986",
    nameBn: "সলোমন আইল্যান্ড",
    nameEn: "SOLOMON ISLANDS",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8981",
    nameBn: "সোমালিয়া",
    nameEn: "SOMALIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5645",
    nameBn: "দক্ষিণ আফ্রিকা",
    nameEn: "SOUTH AFRICA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5865",
    nameBn: "দক্ষিণ কোরিয়া",
    nameEn: "SOUTH KOREA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8880",
    nameBn: "দক্ষিণ সুদান",
    nameEn: "SOUTH SUDAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5903",
    nameBn: "স্পেন",
    nameEn: "SPAIN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5870",
    nameBn: "শ্রীলঙ্কা",
    nameEn: "SRI LANKA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "10480",
    nameBn: "সুদান",
    nameEn: "SUDAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5678",
    nameBn: "সুইডেন",
    nameEn: "SWEDEN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5926",
    nameBn: "সুইজারল্যান্ড",
    nameEn: "SWITZERLAND",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8983",
    nameBn: "সিরিয়া",
    nameEn: "SYRIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8380",
    nameBn: "তাজিকিস্তান",
    nameEn: "TAJIKISTAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8930",
    nameBn: "তাঞ্জানিয়া",
    nameEn: "TANZANIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5735",
    nameBn: "থাইল্যান্ড",
    nameEn: "THAILAND",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9181",
    nameBn: "পূর্ব তিমুর",
    nameEn: "TIMOR-LESTE",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9131",
    nameBn: "টোগো",
    nameEn: "TOGO",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8230",
    nameBn: "ত্রিনিদাদ ও টোবাগো",
    nameEn: "TRINIDAD AND TOBAGO",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9030",
    nameBn: "তিউনিসিয়া",
    nameEn: "TUNISIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5682",
    nameBn: "তুরস্ক",
    nameEn: "TURKEY",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8782",
    nameBn: "তুর্কমেনিস্তান",
    nameEn: "TURKMENISTAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9084",
    nameBn: "টুভালু",
    nameEn: "TUVALU",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8980",
    nameBn: "উগান্ডা",
    nameEn: "UGANDA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8785",
    nameBn: "ইউক্রেন",
    nameEn: "UKRAINE",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5654",
    nameBn: "সংযুক্ত আরব আমিরাত",
    nameEn: "UNITED ARAB EMIRATES",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5647",
    nameBn: "যুক্তরাজ্য",
    nameEn: "UNITED KINGDOM",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "5638",
    nameBn: "যুক্তরাষ্ট্র",
    nameEn: "UNITED STATES",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8984",
    nameBn: "উরুগুয়ে",
    nameEn: "URUGUAY",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "7836",
    nameBn: "উজবেকিস্তান",
    nameEn: "UZBEKISTAN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8884",
    nameBn: "ভানুয়াতু",
    nameEn: "VANUATU",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8430",
    nameBn: "ভেনিজুয়ালা",
    nameEn: "VENEZUELA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "13179",
    nameBn: "ভিয়েতনাম",
    nameEn: "VIET NAM",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "9032",
    nameBn: "ইয়েমেন",
    nameEn: "YEMEN",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8031",
    nameBn: "জাম্বিয়া",
    nameEn: "ZAMBIA",
    geoId: "10",
    geoParentId: "5556",
  },
  {
    id: "8580",
    nameBn: "জিম্বাবুয়ে",
    nameEn: "ZIMBABWE",
    geoId: "10",
    geoParentId: "5556",
  },
];

export const nationalityOptions = [
  { id: "-1", value: "অজানা" },
  { id: "1", value: "বাংলাদেশী" },
  { id: "2", value: "মালয়েশিয়া" },
  { id: "3", value: "কুয়েত" },
  { id: "5", value: "ওমান" },
  { id: "7", value: "যুক্তরাষ্ট্র" },
  { id: "12", value: "কানাডা" },
  { id: "14", value: "দক্ষিণ আফ্রিকা" },
  { id: "16", value: "যুক্তরাজ্য" },
  { id: "20", value: "সৌদি আরব" },
  { id: "23", value: "সংযুক্ত আরব আমিরাত" },
  { id: "26", value: "সিঙ্গাপুর" },
  { id: "28", value: "চীন" },
  { id: "31", value: "ভারত" },
  { id: "45", value: "জর্ডান" },
  { id: "47", value: "সুইডেন" },
  { id: "51", value: "তুরস্ক" },
  { id: "53", value: "গ্রীস" },
  { id: "55", value: "কাতার" },
  { id: "77", value: "বাহরাইন" },
  { id: "95", value: "অস্ট্রেলিয়া" },
  { id: "97", value: "নেদারল্যান্ডস" },
  { id: "99", value: "মায়ানমার" },
  { id: "102", value: "কেনিয়া" },
  { id: "104", value: "থাইল্যান্ড" },
  { id: "106", value: "পোল্যান্ড" },
  { id: "108", value: "ফ্রান্স" },
  { id: "153", value: "ব্রুনাই" },
  { id: "156", value: "মিশর" },
  { id: "158", value: "বেলজিয়াম" },
  { id: "222", value: "পর্তুগাল" },
  { id: "234", value: "দক্ষিণ কোরিয়া" },
  { id: "237", value: "মরক্কো" },
  { id: "239", value: "শ্রীলঙ্কা" },
  { id: "245", value: "ইটালি" },
  { id: "250", value: "জাপান" },
  { id: "259", value: "মরিশাস" },
  { id: "272", value: "স্পেন" },
  { id: "275", value: "লেবানন" },
  { id: "280", value: "ইন্দোনেশিয়া" },
  { id: "285", value: "জার্মানী" },
  { id: "288", value: "ফিলিপাইন" },
  { id: "289", value: "লিবিয়া" },
  { id: "292", value: "পাকিস্তানী" },
  { id: "295", value: "সুইজারল্যান্ড" },
  { id: "297", value: "অস্ট্রিয়া" },
  { id: "305", value: "ডেনমার্ক" },
  { id: "306", value: "ইউক্রেনিয়ান" },
  { id: "307", value: "আয়ারল্যান্ড" },
  { id: "308", value: "নেপাল" },
  { id: "309", value: "নাইজেরিয়া" },
  { id: "310", value: "তিমুর" },
  { id: "311", value: "আর্জেন্টিনা" },
  { id: "312", value: "ক্যামেরুন" },
  { id: "313", value: "নরওয়ে" },
  { id: "314", value: "রাশিয়া" },
  { id: "315", value: "আইভরি কোস্ট" },
  { id: "316", value: "সেনেগাল" },
  { id: "317", value: "সুদান" },
  { id: "318", value: "তাইওয়ান" },
  { id: "319", value: "ইরান" },
  { id: "320", value: "ফিনল্যান্ড" },
  { id: "321", value: "বুলগেরিয়া" },
  { id: "322", value: "আজারবাইজান" },
  { id: "323", value: "লিথুনিয়া" },
  { id: "324", value: "মেক্সিকো" },
  { id: "325", value: "জ্যমাইকা" },
  { id: "326", value: "সার্বিয়া" },
  { id: "327", value: "সিরিয়া" },
  { id: "328", value: "বলিভিয়া" },
  { id: "329", value: "ফিলিস্তিন" },
  { id: "330", value: "রোমানিয়া" },
  { id: "331", value: "হংকং" },
  { id: "332", value: "নিউজিল্যান্ড" },
  { id: "333", value: "ইরাক" },
  { id: "334", value: "কাজাখস্তান" },
  { id: "335", value: "নিকারাগুয়া" },
  { id: "336", value: "কিউবা" },
  { id: "337", value: "ত্রিনিদাদ ও টোবাগো" },
  { id: "338", value: "বাহামা" },
  { id: "339", value: "ইকুয়েটোরিয়াল গিনি" },
  { id: "340", value: "এন্ডোরা" },
  { id: "341", value: "মরিশাস" },
  { id: "342", value: "ভিয়েতনামী" },
  { id: "343", value: "আলবেনিয়ান" },
  { id: "344", value: "তানজানিয়ান" },
  { id: "345", value: "তুর্কমেনিস্তান" },
  { id: "346", value: "ম্যাসেডোনিয়ান" },
  { id: "347", value: "ইয়েমেনি" },
  { id: "348", value: "জর্জিয়ান" },
  { id: "351", value: "কমোরিয়ান" },
  { id: "353", value: "ব্রাজিলিয়ান" },
  { id: "356", value: "তিউনিসিয়ান" },
  { id: "357", value: "ইথিওপিয়ান" },
  { id: "358", value: "কম্বোডিয়ান" },
  { id: "359", value: "লাটভিয়ান" },
  { id: "360", value: "উগান্ডা" },
  { id: "361", value: "উগান্ডান" },
  { id: "362", value: "রুয়ান্ডান" },
  { id: "363", value: "জিম্বাবুয়ে" },
  { id: "364", value: "জিম্বাবুয়ে" },
  { id: "365", value: "ভুটানি" },
  { id: "366", value: "ভুটানি" },
  { id: "367", value: "সোমালিয়ান" },
  { id: "368", value: "সোমালিয়ান" },
  { id: "369", value: "মালদিভিয়ান" },
  { id: "370", value: "মালদিভিয়ান" },
  { id: "371", value: "ফিলিস্তিনি" },
  { id: "372", value: "সিরিয়ান" },
];

export const dutaBasCountries = [
  {
    id: "7380",
    nameBn: "আলজেরিয়া",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5726",
    nameBn: "অস্ট্রেলিয়া",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5928",
    nameBn: "অস্ট্রিয়া",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5708",
    nameBn: "বাহরাইন",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5789",
    nameBn: "বেলজিয়াম",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "7042",
    nameBn: "ভুটান",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "7045",
    nameBn: "ব্রাজিল",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5784",
    nameBn: "ব্রুনাই",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5643",
    nameBn: "কানাডা",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5659",
    nameBn: "চীন",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5936",
    nameBn: "ডেনমার্ক",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5787",
    nameBn: "মিশর",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5739",
    nameBn: "ফ্রান্স",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5916",
    nameBn: "জার্মানী",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5684",
    nameBn: "গ্রীস",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5662",
    nameBn: "ভারত",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5911",
    nameBn: "ইন্দোনেশিয়া",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "6730",
    nameBn: "ইরান",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "6782",
    nameBn: "ইরাক",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5876",
    nameBn: "ইটালি",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5881",
    nameBn: "জাপান",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5676",
    nameBn: "জর্ডান",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5733",
    nameBn: "কেনিয়া",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5634",
    nameBn: "কুয়েত",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5906",
    nameBn: "লেবানন",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5920",
    nameBn: "লিবিয়া",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5632",
    nameBn: "মালয়েশিয়া",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "7138",
    nameBn: "মালদ্বীপ",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5890",
    nameBn: "মরিশাস",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "7180",
    nameBn: "মেক্সিকো",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5868",
    nameBn: "মরক্কো",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5730",
    nameBn: "মায়ানমার",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "7182",
    nameBn: "নেপাল",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5728",
    nameBn: "নেদারল্যান্ডস",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "7184",
    nameBn: "নাইজেরিয়া",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5636",
    nameBn: "ওমান",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5923",
    nameBn: "পাকিস্তান",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5919",
    nameBn: "ফিলিপাইন",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5737",
    nameBn: "পোল্যান্ড",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5853",
    nameBn: "পর্তুগাল",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5686",
    nameBn: "কাতার",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "7830",
    nameBn: "রোমানিয়া",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "6477",
    nameBn: "রাশিয়ান ফেডারেশন",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5651",
    nameBn: "সৌদি আরব",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5657",
    nameBn: "সিঙ্গাপুর",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5645",
    nameBn: "দক্ষিণ আফ্রিকা",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5865",
    nameBn: "দক্ষিণ কোরিয়া",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5903",
    nameBn: "স্পেন",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5870",
    nameBn: "শ্রীলঙ্কা",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5678",
    nameBn: "সুইডেন",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5926",
    nameBn: "সুইজারল্যান্ড",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5735",
    nameBn: "থাইল্যান্ড",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5682",
    nameBn: "তুরস্ক",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5654",
    nameBn: "সংযুক্ত আরব আমিরাত",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5647",
    nameBn: "যুক্তরাজ্য",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "5638",
    nameBn: "যুক্তরাষ্ট্র",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "7836",
    nameBn: "উজবেকিস্তান",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
  {
    id: "13179",
    nameBn: "ভিয়েতনাম",
    geoLevelId: "10",
    parentGeoId: "5556",
  },
];
